#
path_to_datafile: 'data/ames/ames_train_raw.csv'


path_to_smiles_dict: 'data/SMILES/Dictionary'
max_smiles_len: 60
mode: 'denovo'
smiles_one_hot: True
batch_size: 10

#AE
path_to_ae: 'ae/ae.pth'

#Predictors
paths_to_predictors: ['c2f/c2f_bbbp.pth']

#seq2seq
path_to_seq2seq: ' '
hidden_size: 512
embd_size: 512
cell_type: 'LSTM'
num_layers: 2
teacher_forcing_p: 0.
smiles_dict_size: 58
encoder_dropout_p: 0.


